name: Publish Quarto Report

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  publish-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Install extension
        run: |
          cd report/
          quarto add dfolio/quarto-ieee --no-prompt

      - name: Render and Publish
        id: github-pages
        uses: quarto-dev/quarto-actions/publish@v2.1.6
        with:
          target: gh-pages
          path: report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
